### ISSUE TITLE
Keyserver Timeout

### ISSUE THREAD

**Issue by rotcivo** [geerlingguy/ansible-role-passenger#18]
When running this role, I get a timeout error when trying to add the passenger apt key in this step:
https://github.com/geerlingguy/ansible-role-passenger/blob/c48f3316e8db629fb6ba24c09ac79cdfc13042ff/tasks/main.yml#L11-L16

If i modify the keyserver item to use `hkp://keyserver.ubuntu.com:80`, the task does not timeout and I am able to grab the key successfully.

I'm not sure if this is isolated to my install only or others experiencing a similar issue?

system deets below:

OS: 
```
root@ip-172-30-8-240:/usr/local/lib/ansible# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
ansible version:
```
root@ip-172-30-8-240:/usr/local/lib/ansible# ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

**Comment by geerlingguy** [comment]
Interesting; at least in a couple different CI environments, I haven't had this issue.
